name: dart_extensions
description:  set of method-extentions for flutter that makes using framework in a much easier and clean way also adds additional functionality.
version: 0.0.8
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  quiver: ^2.0.0

dev_dependencies:
  test: ^1.9.2

flutter: